server:
  port: 9093

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.cnot7bnrds6j.us-east-1.rds.amazonaws.com:5432/database-1
    username: postgres
    password: utec123456
  jpa:
    hibernate:
      ddl-auto: update  # O el que mejor se ajuste a tu estrategia de gestión de esquema
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Configuración de Eureka
eureka:
  instance:
    hostname: 54.236.5.210
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
