# aqui haremos las peticiones
server:
  port: 8080

my_ip:
  value: 3.91.71.245


spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: usuarios
            uri: http://${my_ip.value}:9092
            predicates:
              - Path=/api/usuarios/**
          - id: respuesta
            uri: http://${my_ip.value}:9091
            predicates:
              - Path=/api/respuestas/**
          - id: hilos
            uri: http://${my_ip.value}:9090
            predicates:
              - Path=/api/hilos/**
          - id: estados
            uri: http://${my_ip.value}:9093
            predicates:
              - Path=/api/estados/**

# Configuración de Eureka
eureka:
  instance:
    hostname: 3.91.71.245
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
